// The TanStack Router instance used by TanStack Start. Start calls getRouter()
// on both the server and the client. routeTree.gen.ts is generated by the
// TanStack Start Vite plugin on first dev/build - it won't exist before then.
import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

export function getRouter() {
  const router = createRouter({
    routeTree,
    scrollRestoration: true,
    defaultPreload: "intent",
  });

  return router;
}
